### ISSUE TITLE
Тексты для сервиса

### ISSUE THREAD

**Issue by totaki** [totaki/ikakpalka#13]
@nvpushkarskiy 
Необходиммо написать тексты типо "Вы регистрируетесь на сервесе", "Заполняете свои контакты", "По телефону или лично сообщаете свой номер". Запихать это под футер где у нас сейчас "ПРОСТОЙ КОНТАКТ". Сейчас нихрена не поймешь что это и зачем надо.

**Comment by nikpushkarski** [comment]
@totaki 
написал тексты, направил пулл реквест
также прикладываю файлы здесь (на всякий случай)

[FAQ_docx.docx](https://github.com/totaki/ikakpalka/files/541175/FAQ_docx.docx)
[FAQ_txt.txt](https://github.com/totaki/ikakpalka/files/541176/FAQ_txt.txt)

**Comment by totaki** [comment]
Никита когда добавляешь .gitignore добавляй его в сам .gitignore.
